#!/usr/bin/env python
#-*- coding:utf-8 -*-

from pynlpl.formats import folia
import codecs

print "Generating Relax NG schema"
folia.relaxng('folia-min.rng')

#!/usr/bin/python
data = codecs.open("folia-min.rng",'r','utf-8').readlines()
data.insert(1,"""<!--
RelaxNG schema for FoLiA XML v%s
    by Maarten van Gompel
    Induction of Linguistic Knowledge Research group
    Tilburg University
    
    http://ilk.uvt.nl/folia
    http://github.com/proycon/folia
    
    Schema version %s 
      (auto-generated by pynlpl.formats.folia)
        
    Validation examples:
     $ xmllint --relaxng folia.rng foliadocument.xml     
     $ jing folia.rng foliadocument.xml
    
    Licensed under the GNU General Public License v3
-->
""" %  (folia.FOLIAVERSION, folia.LIBVERSION))
codecs.open('folia.rng','w','utf-8').writelines(data)


print "Validating example document"
folia.validate('../test/example.xml')
